//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_f_Denis.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public long ID { get; set; }
        public Nullable<long> ID_user { get; set; }
        public Nullable<long> ID_product { get; set; }
        public string Note { get; set; }
        public string Comment { get; set; }
    }
}
